#!/usr/bin/env python3
"""Write the canonical figures every page must agree with, from js/heat-model.js.

docs/model-canon.json holds every model output for every property type, bedroom count
and insulation level: gas and heat kWh, heat pump size, installed cost median and range,
cost after each grant, and annual running costs. docs/model-canon.md is the same for a
person, with the hub rows the guides quote. Pass --old <path to an earlier heat-model.js>
to include that model's figures alongside, so a page still quoting an old number can be
found and corrected.

Pass --prior <an earlier model-canon.json> to keep that file's figures alongside as "prior",
which is how the 25 September 2026 price change (oil, heat pump tariff, boiler) was tracked.

Usage: python3 docs/superpowers/tools/canon.py [--old path] [--prior path]
"""
import json, subprocess, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[3]
import sys as _sys, os as _os; _sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
import prices as _prices
GAS_P, ELEC_P, HPT_P, OIL_P, LPG_P = _prices.GAS, _prices.ELEC, _prices.HPT, _prices.OIL, _prices.LPG
GAS_SC = 108.33
TYPES = ['detached', 'semi', 'mid-terrace', 'end-terrace', 'bungalow', 'flat']
INS = ['poor', 'average', 'good', 'excellent']

JS = """
global.window={};require(%r);const H=window.RP_HEAT;const o={};
for(const t of %s)for(const b of [1,2,3,4,5])for(const i of %s){
  o[t+'|'+b+'|'+i]={gas:H.gasKwh(t,b,i),heat:H.heatDemand(t,b,i),cop:H.cop(i),
    install:H.heatPumpInstall(t,b,i),
    range:H.heatPumpInstallRange?H.heatPumpInstallRange(t,b,i):null,
    kw:H.heatPumpKw?H.heatPumpKw(t,b,i):null};}
console.log(JSON.stringify(o));
"""


def run(model_path):
    out = subprocess.run(['node', '-e', JS % (str(model_path), json.dumps(TYPES), json.dumps(INS))],
                         capture_output=True, text=True, cwd=ROOT)
    if out.returncode:
        sys.exit(out.stderr)
    return json.loads(out.stdout)


def figures(c):
    heat, cop = c['heat'], c['cop']
    f = {
        'gas_kwh': c['gas'], 'heat_kwh': heat, 'cop': cop, 'kw': c['kw'],
        'gas_cost': round(c['gas'] * GAS_P), 'gas_cost_with_standing': round(c['gas'] * GAS_P + GAS_SC),
        'oil_cost': round(heat / 0.85 * OIL_P), 'lpg_cost': round(heat / 0.85 * LPG_P),
        'hp_standard': round(heat / cop * ELEC_P), 'hp_tariff': round(heat / cop * HPT_P),
        'electric_boiler': round(heat * ELEC_P), 'hp_kwh_electricity': round(heat / cop),
        'install_median': c['install'],
    }
    if c.get('range'):
        lo, hi = c['range']
        f.update(install_low=lo, install_high=hi,
                 after_grant_low=max(0, lo - 7500), after_grant_high=max(0, hi - 7500),
                 after_oil_lpg_grant_low=max(0, lo - 9000), after_oil_lpg_grant_high=max(0, hi - 9000),
                 after_grant_median=max(0, c['install'] - 7500))
    return f


def main():
    new = run(ROOT / 'js' / 'heat-model.js')
    old = prior = None
    if '--prior' in sys.argv:
        prior = json.loads(pathlib.Path(sys.argv[sys.argv.index('--prior') + 1]).read_text())
    if '--old' in sys.argv:
        old = run(pathlib.Path(sys.argv[sys.argv.index('--old') + 1]).resolve())
    canon = {}
    for k, c in new.items():
        canon[k] = {'new': figures(c)}
        if old:
            canon[k]['old'] = figures(old[k])
        if prior:
            canon[k]['prior'] = prior[k]['new']
    (ROOT / 'docs' / 'model-canon.json').write_text(json.dumps(canon, indent=1))

    # The rows the guides quote, at average insulation.
    HUB = [('1 to 2 bed flat', [('flat', 1), ('flat', 2)]), ('2 bed mid-terrace', [('mid-terrace', 2)]),
           ('3 bed mid-terrace', [('mid-terrace', 3)]), ('3 bed end-terrace', [('end-terrace', 3)]),
           ('3 bed semi', [('semi', 3)]), ('3 bed detached', [('detached', 3)]), ('4 bed semi', [('semi', 4)]),
           ('4 bed detached', [('detached', 4)]), ('5 bed detached', [('detached', 5)]),
           ('2 bed bungalow', [('bungalow', 2)]), ('3 bed bungalow', [('bungalow', 3)])]
    lines = ['# Model canon', '',
             'Generated by docs/superpowers/tools/canon.py from js/heat-model.js. Every heat pump cost, size and running cost on the site must match this. Average insulation unless stated. Money in pounds a year unless stated.', '',
             '| Home | kW | Installed, middle half of real installs | Median | After £7,500 grant | After £9,000 (oil, LPG) | Gas | Heat pump, standard | Heat pump tariff | Electric boiler |'
             + (' Old installed | Old heat pump std | Old tariff |' if old else ''),
             '|---|---|---|---|---|---|---|---|---|---|' + ('---|---|---|' if old else '')]
    for label, cells in HUB:
        fs = [canon['%s|%d|average' % c]['new'] for c in cells]
        lo, hi = min(f['install_low'] for f in fs), max(f['install_high'] for f in fs)
        kws = sorted(set(f['kw'] for f in fs))
        row = '| %s | %s | £%s to £%s | £%s | £%s to £%s | £%s to £%s | £%s | £%s | £%s | £%s |' % (
            label, ' to '.join('%g' % k for k in kws), f'{lo:,}', f'{hi:,}', f"{fs[-1]['install_median']:,}",
            f'{max(0, lo - 7500):,}', f'{max(0, hi - 7500):,}', f'{max(0, lo - 9000):,}', f'{max(0, hi - 9000):,}',
            f"{fs[-1]['gas_cost']:,}", f"{fs[-1]['hp_standard']:,}", f"{fs[-1]['hp_tariff']:,}", f"{fs[-1]['electric_boiler']:,}")
        if old:
            os_ = [canon['%s|%d|average' % c]['old'] for c in cells]
            row += ' £%s | £%s | £%s |' % (f"{os_[-1]['install_median']:,}", f"{os_[-1]['hp_standard']:,}", f"{os_[-1]['hp_tariff']:,}")
        lines.append(row)
    lines += ['', 'Efficiency (SPFH4) by insulation: poor 2.55, average 2.78, good 3.05, excellent 3.25. Prices: gas %sp, electricity %sp, heat pump tariff %sp, oil %sp, LPG %sp per kWh; gas standing charge £108.33 a year.' % tuple(('%.2f' % (x * 100)).rstrip('0').rstrip('.') for x in (GAS_P, ELEC_P, HPT_P, OIL_P, LPG_P)),
              'Installed cost: median reported under the Boiler Upgrade Scheme in 2025/26 for a heat pump of that size (DESNZ, August 2026, Table A1.3A). Range: the scheme\'s Q2 2026 quartiles scaled to the median.']
    (ROOT / 'docs' / 'model-canon.md').write_text('\n'.join(lines) + '\n')
    print('\n'.join(lines))


if __name__ == '__main__':
    main()
