EDITS = {'guides/heat-pump-running-costs/index.html': [
 ('<tr><td>Mid-terrace (2 bed)</td><td>8,000</td><td>£601</td><td>£676</td><td class="highlight-cell">£441 to £529</td></tr>',
  '<tr><td>Mid-terrace (2 bed)</td><td>8,000</td><td>£708</td><td>£726</td><td class="highlight-cell">£469 to £552</td></tr>'),
 ('<tr><td>Semi-detached (3 bed)</td><td>12,000</td><td>£901</td><td>£1,014</td><td class="highlight-cell">£662 to £794</td></tr>',
  '<tr><td>Semi-detached (3 bed)</td><td>12,000</td><td>£1,063</td><td>£1,089</td><td class="highlight-cell">£703 to £828</td></tr>'),
 ('<tr><td>Semi-detached (3 bed, old)</td><td>15,000</td><td>£1,127</td><td>£1,267</td><td class="highlight-cell">£828 to £993</td></tr>',
  '<tr><td>Semi-detached (3 bed, old)</td><td>15,000</td><td>£1,328</td><td>£1,361</td><td class="highlight-cell">£879 to £1,034</td></tr>'),
 ('<tr><td>Detached (4 bed)</td><td>18,000</td><td>£1,352</td><td>£1,521</td><td class="highlight-cell">£993 to £1,192</td></tr>',
  '<tr><td>Detached (4 bed)</td><td>18,000</td><td>£1,594</td><td>£1,634</td><td class="highlight-cell">£1,055 to £1,241</td></tr>'),
 ('<tr><td>Detached (4 bed, old)</td><td>22,000</td><td>£1,653</td><td>£1,859</td><td class="highlight-cell">£1,214 to £1,457</td></tr>',
  '<tr><td>Detached (4 bed, old)</td><td>22,000</td><td>£1,948</td><td>£1,997</td><td class="highlight-cell">£1,290 to £1,517</td></tr>'),
 ('Gas boiler assumes 90% efficiency at 6.76p/kWh. Heat pump assumes COP 2.9. Standard tariff: 24.5p/kWh. Heat pump tariff: 15 to 18p/kWh effective rate. Based on Ofgem Q1 2026 price cap.',
  'Gas boiler assumes 90% efficiency at 7.97p/kWh. Heat pump assumes COP 2.9. Standard tariff: 26.32p/kWh. Heat pump tariff: 17 to 20p/kWh effective rate. Based on the Ofgem price cap for October to December 2026.'),
 ('<th>Cost per kWh of heat (HP tariff, 16p)</th>', '<th>Cost per kWh of heat (HP tariff, 18p)</th>'),
 ('<tr><td>2.5 (poor installation)</td><td>9.8p</td><td>6.4p</td></tr>', '<tr><td>2.5 (poor installation)</td><td>10.5p</td><td>7.2p</td></tr>'),
 ('<tr><td>2.8 (average)</td><td>8.8p</td><td>5.7p</td></tr>', '<tr><td>2.8 (average)</td><td>9.4p</td><td>6.4p</td></tr>'),
 ('<tr><td>3.0 (good)</td><td>8.2p</td><td class="highlight-cell">5.3p</td></tr>', '<tr><td>3.0 (good)</td><td>8.8p</td><td class="highlight-cell">6.0p</td></tr>'),
 ('<tr><td>3.2 (excellent)</td><td>7.7p</td><td class="highlight-cell">5.0p</td></tr>', '<tr><td>3.2 (excellent)</td><td>8.2p</td><td class="highlight-cell">5.6p</td></tr>'),
 ('<tr><td>4.0 (ground source)</td><td>6.1p</td><td class="highlight-cell">4.0p</td></tr>', '<tr><td>4.0 (ground source)</td><td>6.6p</td><td class="highlight-cell">4.5p</td></tr>'),
 ('For reference: gas boiler at 90% efficiency costs 7.5p per kWh of heat at 6.76p/kWh gas price.',
  'For reference: gas boiler at 90% efficiency costs 8.9p per kWh of heat at 7.97p/kWh gas price.'),
 ('<tr><td>Gas (mains)</td><td>6.76p</td><td>7.5p</td></tr>', '<tr><td>Gas (mains)</td><td>7.97p</td><td>8.9p</td></tr>'),
 ('<tr><td>Oil (kerosene)</td><td>6.8p</td><td>8.0p</td></tr>', '<tr><td>Oil (kerosene)</td><td>9.0p</td><td>10.6p</td></tr>'),
 ('<tr><td>Direct electric</td><td>24.5p</td><td>24.5p</td></tr>', '<tr><td>Direct electric</td><td>26.32p</td><td>26.32p</td></tr>'),
 ('<tr><td>Heat pump (standard tariff, COP 2.9)</td><td>24.5p</td><td class="highlight-cell">8.4p</td></tr>',
  '<tr><td>Heat pump (standard tariff, COP 2.9)</td><td>26.32p</td><td class="highlight-cell">9.1p</td></tr>'),
 ('<tr><td>Heat pump (HP tariff, COP 2.9)</td><td>~16p</td><td class="highlight-cell">5.5p</td></tr>',
  '<tr><td>Heat pump (HP tariff, COP 2.9)</td><td>~18p</td><td class="highlight-cell">6.2p</td></tr>'),
 ('Oil and LPG prices fluctuate significantly. Figures based on March 2026 market rates.',
  'Oil and LPG prices fluctuate significantly. Figures based on September 2026 market rates.'),
 ('On a standard electricity tariff, a heat pump costs slightly more to run than a gas boiler. On a dedicated heat pump tariff, it costs <span class="key-number">£200 to £400 less</span> per year.',
  'On a standard electricity tariff, a heat pump now costs about the same to run as a gas boiler. On a dedicated heat pump tariff, it costs <span class="key-number">£200 to £500 less</span> per year.'),
 ('<p>At the Q1 2026 Ofgem price cap, electricity costs 24.5p/kWh and gas costs 6.76p/kWh. Electricity is 3.6 times more expensive than gas. But a heat pump with a COP of 2.9 produces 2.9 kWh of heat for every 1 kWh of electricity. So the effective cost of heat from a heat pump is 24.5p divided by 2.9, which equals 8.4p per kWh of heat. Compare that to gas at 6.76p per kWh (assuming 90% boiler efficiency, the real cost is 7.5p per kWh of heat).</p>',
  '<p>At the Ofgem price cap for October to December 2026, electricity costs 26.32p/kWh and gas costs 7.97p/kWh. Electricity is 3.3 times more expensive than gas. But a heat pump with a COP of 2.9 produces 2.9 kWh of heat for every 1 kWh of electricity. So the effective cost of heat from a heat pump is 26.32p divided by 2.9, which equals 9.1p per kWh of heat. Compare that to gas at 7.97p per kWh (assuming 90% boiler efficiency, the real cost is 8.9p per kWh of heat).</p>'),
 ('<p>On a standard tariff, heat pump heating costs 8.4p per kWh versus gas at 7.5p per kWh. Gas wins by a narrow margin. On a heat pump tariff at an effective rate of 16p/kWh, heat pump heating costs 5.5p per kWh, beating gas comfortably.</p>',
  '<p>On a standard tariff, heat pump heating costs 9.1p per kWh versus gas at 8.9p per kWh. That is level, within the margin of any real installation. On a heat pump tariff at an effective rate of 18p/kWh, heat pump heating costs 6.2p per kWh, beating gas comfortably.</p>'),
 ('Effective rates of 15 to 18p/kWh are achievable.', 'Effective rates of 17 to 20p/kWh are achievable.'),
 ('<p>A 3-bed semi costs £1,267 on a standard tariff or £828 to £1,034 on a heat pump tariff.',
  '<p>A 3-bed semi costs £1,361 on a standard tariff or £879 to £1,034 on a heat pump tariff.'),
 ('On a standard electricity tariff, heat pumps cost slightly more to run than a gas boiler in most UK homes. On a dedicated heat pump tariff with cheaper off-peak rates, heat pumps are cheaper. For a 3-bed semi, annual heating costs are approximately £1,127 for gas, £1,267 for a heat pump on standard tariff, and £828 to £1,034 for a heat pump on a heat pump tariff.',
  'On a standard electricity tariff, heat pumps now cost about the same to run as a gas boiler in most UK homes. On a dedicated heat pump tariff with cheaper off-peak rates, heat pumps are cheaper. For a 3-bed semi, annual heating costs are approximately £1,328 for gas, £1,361 for a heat pump on standard tariff, and £879 to £1,034 for a heat pump on a heat pump tariff.'),
 ('A well-insulated 3-bed semi with a COP 2.9 heat pump costs £1,267 per year on a standard tariff or £828 to £1,034 on a heat pump tariff.',
  'A well-insulated 3-bed semi with a COP 2.9 heat pump costs £1,361 per year on a standard tariff or £879 to £1,034 on a heat pump tariff.'),
 ('This can reduce your effective electricity rate from 24.5p/kWh to around 15 to 18p/kWh for heating.',
  'This can reduce your effective electricity rate from 26.32p/kWh to around 17 to 20p/kWh for heating.'),
]}
