EDITS = {'guides/electric-boiler-vs-heat-pump/index.html': [
 ('<tr><td>2-bed terrace</td><td>£1,960</td><td>£676</td><td>£441</td><td class="highlight-cell">£1,519</td></tr>',
  '<tr><td>2-bed terrace</td><td>£2,106</td><td>£726</td><td>£497</td><td class="highlight-cell">£1,609</td></tr>'),
 ('<tr><td>3-bed semi</td><td>£2,940</td><td>£1,014</td><td>£662</td><td class="highlight-cell">£2,278</td></tr>',
  '<tr><td>3-bed semi</td><td>£3,158</td><td>£1,089</td><td>£745</td><td class="highlight-cell">£2,413</td></tr>'),
 ('<tr><td>3-bed detached</td><td>£3,675</td><td>£1,267</td><td>£828</td><td class="highlight-cell">£2,847</td></tr>',
  '<tr><td>3-bed detached</td><td>£3,948</td><td>£1,361</td><td>£931</td><td class="highlight-cell">£3,017</td></tr>'),
 ('<tr><td>4-bed detached</td><td>£4,410</td><td>£1,521</td><td>£993</td><td class="highlight-cell">£3,417</td></tr>',
  '<tr><td>4-bed detached</td><td>£4,738</td><td>£1,634</td><td>£1,117</td><td class="highlight-cell">£3,621</td></tr>'),
 ('Electric boiler assumes 100% efficiency at 24.5p/kWh. Heat pump COP 2.9. Standard tariff 24.5p/kWh. HP tariff ~16p/kWh. Ofgem Q1 2026 rates.',
  'Electric boiler assumes 100% efficiency at 26.32p/kWh. Heat pump COP 2.9. Standard tariff 26.32p/kWh. HP tariff ~18p/kWh. Ofgem price cap, October to December 2026.'),
 ('that is the difference between £2,940 per year (electric boiler) and £662 per year (heat pump on a heat pump tariff).',
  'that is the difference between £3,158 per year (electric boiler) and £745 per year (heat pump on a heat pump tariff).'),
 ('Every unit of heat costs you the full electricity price: 24.5p at Ofgem Q1 2026 rates.',
  'Every unit of heat costs you the full electricity price: 26.32p at the Ofgem price cap for October to December 2026.'),
 ('the heat pump saves £1,284 to £2,889 per year compared to an electric boiler.',
  'the heat pump saves £1,380 to £3,104 per year compared to an electric boiler.'),
 ('with £2,278 per year in running cost savings (3-bed semi on HP tariff)',
  'with £2,413 per year in running cost savings (3-bed semi on HP tariff)'),
 ('Gas boiler homes save £239/yr by switching. Electric boiler homes save £2,278/yr.',
  'Gas boiler homes save £318/yr by switching. Electric boiler homes save £2,413/yr.'),
 ('may cost only £735 on an electric boiler. The saving from a heat pump (£490 on HP tariff) would be £245 per year, making the payback much longer.',
  'may cost only £790 on an electric boiler. A heat pump on a heat pump tariff would cost around £186, a saving of about £600 per year, so the payback stretches to 6 to 14 years rather than 1 to 3.'),
 ('A 3-bed semi saves £2,278/yr on a', 'A 3-bed semi saves £2,413/yr on a'),
 ('<p>£2,000 to £4,400 depending on property size. It is the most expensive common heating system because electricity costs 3.6 times more per kWh than gas.</p>',
  '<p>£2,100 to £4,700 depending on property size. It is the most expensive common heating system because electricity costs 3.3 times more per kWh than gas.</p>'),
 ('For a 3-bed semi, an electric boiler costs around £2,940 per year to run. A heat pump on a standard tariff costs £1,014. On a heat pump tariff, it costs £662.',
  'For a 3-bed semi, an electric boiler costs around £3,158 per year to run. A heat pump on a standard tariff costs £1,089. On a heat pump tariff, it costs £745.'),
 ('An electric boiler costs £2,000 to £3,500 per year to run for a typical UK home, depending on property size and insulation level. This is based on electricity at 24.5p/kWh and a boiler efficiency of 99 to 100%. Electric boilers are the most expensive common heating system to run because electricity costs 3.6 times more per kWh than gas.',
  'An electric boiler costs £2,100 to £4,700 per year to run for a typical UK home, depending on property size and insulation level. This is based on electricity at 26.32p/kWh and a boiler efficiency of 99 to 100%. Electric boilers are the most expensive common heating system to run because electricity costs 3.3 times more per kWh than gas.'),
 ('The running cost saving is £1,500 to £2,300 per year for a typical home.',
  'The running cost saving is £1,600 to £3,000 per year for a typical home.'),
 ('saves £1,500 to £2,300 per year, giving a payback', 'saves £1,600 to £3,000 per year, giving a payback'),
]}
